name: cron_parser
description: A cron parser. Spits out next cron dates starting from now or a specific date.
version: 0.1.0
author: Ronny Bubke <ronny@bubke.de>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.14.2